# Site settings
title: Anthony Pasquariello
email: antpas@bu.edu
url: https://antpas.github.io
description: "My name is Anthony Pasquariello. I'm a Computer Engineering student at Boston University. I'm passionate about technology and it's affects on our society."
skills: "Computer Engineering Student - Third Year"
meta_author: Pasquariello Anthony

# Google webmaster tools
google_verify: nmAxgCgXsYLLJBAerrtVahiJH_zw_bcFbPkPe3zmFX8

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 48C334A2C190F6BA9104B73F2B405F08

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Anthony Pasquariello
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/in/anthonypasquariello
  - title: twitter
    url: https://twitter.com/PasAnthony
  - title: stack-overflow
    url: http://stackoverflow.com/users/6018955/anthony-pasquariello?tab=profile
  - title: github
    url: https://github.com/antpas
  - title: bitbucket
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: 8 St. Mary's Street
  - line: Boston, MA 02215

# Credits content
credits: 'Proudly created with the help of Start Bootstrap Theme and GitHub Pages.'

# Build settings
markdown: kramdown
permalink: pretty
